// Code generated by protoc-gen-go. DO NOT EDIT.
// source: APISHTEQio.proto

package MqGrpcProject

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type APISHTEQ_Request struct {
	Eqptid               string   `protobuf:"bytes,1,opt,name=eqptid,proto3" json:"eqptid,omitempty"`
	Sgrid                string   `protobuf:"bytes,2,opt,name=sgrid,proto3" json:"sgrid,omitempty"`
	Nxopeno              string   `protobuf:"bytes,3,opt,name=nxopeno,proto3" json:"nxopeno,omitempty"`
	Lotid                string   `protobuf:"bytes,4,opt,name=lotid,proto3" json:"lotid,omitempty"`
	Serverip             string   `protobuf:"bytes,5,opt,name=serverip,proto3" json:"serverip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APISHTEQ_Request) Reset()         { *m = APISHTEQ_Request{} }
func (m *APISHTEQ_Request) String() string { return proto.CompactTextString(m) }
func (*APISHTEQ_Request) ProtoMessage()    {}
func (*APISHTEQ_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d974130d13394d, []int{0}
}

func (m *APISHTEQ_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APISHTEQ_Request.Unmarshal(m, b)
}
func (m *APISHTEQ_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APISHTEQ_Request.Marshal(b, m, deterministic)
}
func (m *APISHTEQ_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APISHTEQ_Request.Merge(m, src)
}
func (m *APISHTEQ_Request) XXX_Size() int {
	return xxx_messageInfo_APISHTEQ_Request.Size(m)
}
func (m *APISHTEQ_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_APISHTEQ_Request.DiscardUnknown(m)
}

var xxx_messageInfo_APISHTEQ_Request proto.InternalMessageInfo

func (m *APISHTEQ_Request) GetEqptid() string {
	if m != nil {
		return m.Eqptid
	}
	return ""
}

func (m *APISHTEQ_Request) GetSgrid() string {
	if m != nil {
		return m.Sgrid
	}
	return ""
}

func (m *APISHTEQ_Request) GetNxopeno() string {
	if m != nil {
		return m.Nxopeno
	}
	return ""
}

func (m *APISHTEQ_Request) GetLotid() string {
	if m != nil {
		return m.Lotid
	}
	return ""
}

func (m *APISHTEQ_Request) GetServerip() string {
	if m != nil {
		return m.Serverip
	}
	return ""
}

type APISHTEQ_Reply struct {
	Trxid                string         `protobuf:"bytes,1,opt,name=trxid,proto3" json:"trxid,omitempty"`
	Typeid               string         `protobuf:"bytes,2,opt,name=typeid,proto3" json:"typeid,omitempty"`
	Rtncode              string         `protobuf:"bytes,3,opt,name=rtncode,proto3" json:"rtncode,omitempty"`
	Rtnmesg              string         `protobuf:"bytes,4,opt,name=rtnmesg,proto3" json:"rtnmesg,omitempty"`
	Eqptid               string         `protobuf:"bytes,5,opt,name=eqptid,proto3" json:"eqptid,omitempty"`
	Eqptdsc              string         `protobuf:"bytes,6,opt,name=eqptdsc,proto3" json:"eqptdsc,omitempty"`
	Eqptcate             string         `protobuf:"bytes,7,opt,name=eqptcate,proto3" json:"eqptcate,omitempty"`
	Recipeid             string         `protobuf:"bytes,8,opt,name=recipeid,proto3" json:"recipeid,omitempty"`
	Eqptstat             string         `protobuf:"bytes,9,opt,name=eqptstat,proto3" json:"eqptstat,omitempty"`
	Eqptstatdsc          string         `protobuf:"bytes,10,opt,name=eqptstatdsc,proto3" json:"eqptstatdsc,omitempty"`
	Eqptmode             string         `protobuf:"bytes,11,opt,name=eqptmode,proto3" json:"eqptmode,omitempty"`
	Sgrcnt               string         `protobuf:"bytes,12,opt,name=sgrcnt,proto3" json:"sgrcnt,omitempty"`
	Oary1                []*APISHTEQoA1 `protobuf:"bytes,13,rep,name=oary1,proto3" json:"oary1,omitempty"`
	Errmsg               string         `protobuf:"bytes,14,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *APISHTEQ_Reply) Reset()         { *m = APISHTEQ_Reply{} }
func (m *APISHTEQ_Reply) String() string { return proto.CompactTextString(m) }
func (*APISHTEQ_Reply) ProtoMessage()    {}
func (*APISHTEQ_Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d974130d13394d, []int{1}
}

func (m *APISHTEQ_Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APISHTEQ_Reply.Unmarshal(m, b)
}
func (m *APISHTEQ_Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APISHTEQ_Reply.Marshal(b, m, deterministic)
}
func (m *APISHTEQ_Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APISHTEQ_Reply.Merge(m, src)
}
func (m *APISHTEQ_Reply) XXX_Size() int {
	return xxx_messageInfo_APISHTEQ_Reply.Size(m)
}
func (m *APISHTEQ_Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_APISHTEQ_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_APISHTEQ_Reply proto.InternalMessageInfo

func (m *APISHTEQ_Reply) GetTrxid() string {
	if m != nil {
		return m.Trxid
	}
	return ""
}

func (m *APISHTEQ_Reply) GetTypeid() string {
	if m != nil {
		return m.Typeid
	}
	return ""
}

func (m *APISHTEQ_Reply) GetRtncode() string {
	if m != nil {
		return m.Rtncode
	}
	return ""
}

func (m *APISHTEQ_Reply) GetRtnmesg() string {
	if m != nil {
		return m.Rtnmesg
	}
	return ""
}

func (m *APISHTEQ_Reply) GetEqptid() string {
	if m != nil {
		return m.Eqptid
	}
	return ""
}

func (m *APISHTEQ_Reply) GetEqptdsc() string {
	if m != nil {
		return m.Eqptdsc
	}
	return ""
}

func (m *APISHTEQ_Reply) GetEqptcate() string {
	if m != nil {
		return m.Eqptcate
	}
	return ""
}

func (m *APISHTEQ_Reply) GetRecipeid() string {
	if m != nil {
		return m.Recipeid
	}
	return ""
}

func (m *APISHTEQ_Reply) GetEqptstat() string {
	if m != nil {
		return m.Eqptstat
	}
	return ""
}

func (m *APISHTEQ_Reply) GetEqptstatdsc() string {
	if m != nil {
		return m.Eqptstatdsc
	}
	return ""
}

func (m *APISHTEQ_Reply) GetEqptmode() string {
	if m != nil {
		return m.Eqptmode
	}
	return ""
}

func (m *APISHTEQ_Reply) GetSgrcnt() string {
	if m != nil {
		return m.Sgrcnt
	}
	return ""
}

func (m *APISHTEQ_Reply) GetOary1() []*APISHTEQoA1 {
	if m != nil {
		return m.Oary1
	}
	return nil
}

func (m *APISHTEQ_Reply) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type APISHTEQoA1 struct {
	Sgrid                string         `protobuf:"bytes,1,opt,name=sgrid,proto3" json:"sgrid,omitempty"`
	Shtarycnt            string         `protobuf:"bytes,2,opt,name=shtarycnt,proto3" json:"shtarycnt,omitempty"`
	Oary2                []*APISHTEQoA2 `protobuf:"bytes,3,rep,name=oary2,proto3" json:"oary2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *APISHTEQoA1) Reset()         { *m = APISHTEQoA1{} }
func (m *APISHTEQoA1) String() string { return proto.CompactTextString(m) }
func (*APISHTEQoA1) ProtoMessage()    {}
func (*APISHTEQoA1) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d974130d13394d, []int{2}
}

func (m *APISHTEQoA1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APISHTEQoA1.Unmarshal(m, b)
}
func (m *APISHTEQoA1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APISHTEQoA1.Marshal(b, m, deterministic)
}
func (m *APISHTEQoA1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APISHTEQoA1.Merge(m, src)
}
func (m *APISHTEQoA1) XXX_Size() int {
	return xxx_messageInfo_APISHTEQoA1.Size(m)
}
func (m *APISHTEQoA1) XXX_DiscardUnknown() {
	xxx_messageInfo_APISHTEQoA1.DiscardUnknown(m)
}

var xxx_messageInfo_APISHTEQoA1 proto.InternalMessageInfo

func (m *APISHTEQoA1) GetSgrid() string {
	if m != nil {
		return m.Sgrid
	}
	return ""
}

func (m *APISHTEQoA1) GetShtarycnt() string {
	if m != nil {
		return m.Shtarycnt
	}
	return ""
}

func (m *APISHTEQoA1) GetOary2() []*APISHTEQoA2 {
	if m != nil {
		return m.Oary2
	}
	return nil
}

type APISHTEQoA2 struct {
	Shtid                string   `protobuf:"bytes,1,opt,name=shtid,proto3" json:"shtid,omitempty"`
	Shtstat              string   `protobuf:"bytes,2,opt,name=shtstat,proto3" json:"shtstat,omitempty"`
	Lotid                string   `protobuf:"bytes,3,opt,name=lotid,proto3" json:"lotid,omitempty"`
	Spltid               string   `protobuf:"bytes,4,opt,name=spltid,proto3" json:"spltid,omitempty"`
	Nxroutecate          string   `protobuf:"bytes,5,opt,name=nxroutecate,proto3" json:"nxroutecate,omitempty"`
	Nxrouteid            string   `protobuf:"bytes,6,opt,name=nxrouteid,proto3" json:"nxrouteid,omitempty"`
	Nxroutever           string   `protobuf:"bytes,7,opt,name=nxroutever,proto3" json:"nxroutever,omitempty"`
	Cropeno              string   `protobuf:"bytes,8,opt,name=cropeno,proto3" json:"cropeno,omitempty"`
	Nxopeno              string   `protobuf:"bytes,9,opt,name=nxopeno,proto3" json:"nxopeno,omitempty"`
	Nxopeid              string   `protobuf:"bytes,10,opt,name=nxopeid,proto3" json:"nxopeid,omitempty"`
	Nxopever             string   `protobuf:"bytes,11,opt,name=nxopever,proto3" json:"nxopever,omitempty"`
	Nxopedsc             string   `protobuf:"bytes,12,opt,name=nxopedsc,proto3" json:"nxopedsc,omitempty"`
	Nxpeplvl             string   `protobuf:"bytes,13,opt,name=nxpeplvl,proto3" json:"nxpeplvl,omitempty"`
	Nxrecipeid           string   `protobuf:"bytes,14,opt,name=nxrecipeid,proto3" json:"nxrecipeid,omitempty"`
	Nxprocid             string   `protobuf:"bytes,15,opt,name=nxprocid,proto3" json:"nxprocid,omitempty"`
	Productid            string   `protobuf:"bytes,16,opt,name=productid,proto3" json:"productid,omitempty"`
	Eccode               string   `protobuf:"bytes,17,opt,name=eccode,proto3" json:"eccode,omitempty"`
	Unit                 string   `protobuf:"bytes,18,opt,name=unit,proto3" json:"unit,omitempty"`
	Sgrid                string   `protobuf:"bytes,19,opt,name=sgrid,proto3" json:"sgrid,omitempty"`
	Shtcnt               string   `protobuf:"bytes,20,opt,name=shtcnt,proto3" json:"shtcnt,omitempty"`
	Moveinflg            string   `protobuf:"bytes,21,opt,name=moveinflg,proto3" json:"moveinflg,omitempty"`
	Slotno               string   `protobuf:"bytes,22,opt,name=slotno,proto3" json:"slotno,omitempty"`
	Showflag             string   `protobuf:"bytes,23,opt,name=showflag,proto3" json:"showflag,omitempty"`
	Fakeid               string   `protobuf:"bytes,24,opt,name=fakeid,proto3" json:"fakeid,omitempty"`
	Erplotno             string   `protobuf:"bytes,25,opt,name=erplotno,proto3" json:"erplotno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APISHTEQoA2) Reset()         { *m = APISHTEQoA2{} }
func (m *APISHTEQoA2) String() string { return proto.CompactTextString(m) }
func (*APISHTEQoA2) ProtoMessage()    {}
func (*APISHTEQoA2) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d974130d13394d, []int{3}
}

func (m *APISHTEQoA2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APISHTEQoA2.Unmarshal(m, b)
}
func (m *APISHTEQoA2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APISHTEQoA2.Marshal(b, m, deterministic)
}
func (m *APISHTEQoA2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APISHTEQoA2.Merge(m, src)
}
func (m *APISHTEQoA2) XXX_Size() int {
	return xxx_messageInfo_APISHTEQoA2.Size(m)
}
func (m *APISHTEQoA2) XXX_DiscardUnknown() {
	xxx_messageInfo_APISHTEQoA2.DiscardUnknown(m)
}

var xxx_messageInfo_APISHTEQoA2 proto.InternalMessageInfo

func (m *APISHTEQoA2) GetShtid() string {
	if m != nil {
		return m.Shtid
	}
	return ""
}

func (m *APISHTEQoA2) GetShtstat() string {
	if m != nil {
		return m.Shtstat
	}
	return ""
}

func (m *APISHTEQoA2) GetLotid() string {
	if m != nil {
		return m.Lotid
	}
	return ""
}

func (m *APISHTEQoA2) GetSpltid() string {
	if m != nil {
		return m.Spltid
	}
	return ""
}

func (m *APISHTEQoA2) GetNxroutecate() string {
	if m != nil {
		return m.Nxroutecate
	}
	return ""
}

func (m *APISHTEQoA2) GetNxrouteid() string {
	if m != nil {
		return m.Nxrouteid
	}
	return ""
}

func (m *APISHTEQoA2) GetNxroutever() string {
	if m != nil {
		return m.Nxroutever
	}
	return ""
}

func (m *APISHTEQoA2) GetCropeno() string {
	if m != nil {
		return m.Cropeno
	}
	return ""
}

func (m *APISHTEQoA2) GetNxopeno() string {
	if m != nil {
		return m.Nxopeno
	}
	return ""
}

func (m *APISHTEQoA2) GetNxopeid() string {
	if m != nil {
		return m.Nxopeid
	}
	return ""
}

func (m *APISHTEQoA2) GetNxopever() string {
	if m != nil {
		return m.Nxopever
	}
	return ""
}

func (m *APISHTEQoA2) GetNxopedsc() string {
	if m != nil {
		return m.Nxopedsc
	}
	return ""
}

func (m *APISHTEQoA2) GetNxpeplvl() string {
	if m != nil {
		return m.Nxpeplvl
	}
	return ""
}

func (m *APISHTEQoA2) GetNxrecipeid() string {
	if m != nil {
		return m.Nxrecipeid
	}
	return ""
}

func (m *APISHTEQoA2) GetNxprocid() string {
	if m != nil {
		return m.Nxprocid
	}
	return ""
}

func (m *APISHTEQoA2) GetProductid() string {
	if m != nil {
		return m.Productid
	}
	return ""
}

func (m *APISHTEQoA2) GetEccode() string {
	if m != nil {
		return m.Eccode
	}
	return ""
}

func (m *APISHTEQoA2) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *APISHTEQoA2) GetSgrid() string {
	if m != nil {
		return m.Sgrid
	}
	return ""
}

func (m *APISHTEQoA2) GetShtcnt() string {
	if m != nil {
		return m.Shtcnt
	}
	return ""
}

func (m *APISHTEQoA2) GetMoveinflg() string {
	if m != nil {
		return m.Moveinflg
	}
	return ""
}

func (m *APISHTEQoA2) GetSlotno() string {
	if m != nil {
		return m.Slotno
	}
	return ""
}

func (m *APISHTEQoA2) GetShowflag() string {
	if m != nil {
		return m.Showflag
	}
	return ""
}

func (m *APISHTEQoA2) GetFakeid() string {
	if m != nil {
		return m.Fakeid
	}
	return ""
}

func (m *APISHTEQoA2) GetErplotno() string {
	if m != nil {
		return m.Erplotno
	}
	return ""
}

func init() {
	proto.RegisterType((*APISHTEQ_Request)(nil), "MqGrpcProject.APISHTEQ_Request")
	proto.RegisterType((*APISHTEQ_Reply)(nil), "MqGrpcProject.APISHTEQ_Reply")
	proto.RegisterType((*APISHTEQoA1)(nil), "MqGrpcProject.APISHTEQo_a1")
	proto.RegisterType((*APISHTEQoA2)(nil), "MqGrpcProject.APISHTEQo_a2")
}

func init() { proto.RegisterFile("APISHTEQio.proto", fileDescriptor_41d974130d13394d) }

var fileDescriptor_41d974130d13394d = []byte{
	// 626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xcb, 0x8e, 0xd3, 0x3c,
	0x14, 0xc7, 0xd5, 0xc9, 0xb4, 0x9d, 0xba, 0x97, 0x6f, 0x3e, 0x33, 0x33, 0x98, 0x8b, 0x50, 0xd5,
	0xd5, 0xac, 0x2a, 0xb5, 0xf3, 0x04, 0x8c, 0x84, 0x18, 0x24, 0x90, 0x4a, 0x41, 0x62, 0x39, 0x0a,
	0x8e, 0x9b, 0x04, 0xd2, 0xd8, 0x75, 0xdc, 0xd2, 0xbe, 0x03, 0x2f, 0xc0, 0x96, 0x15, 0x8f, 0x89,
	0x8e, 0x7d, 0x9c, 0x38, 0x2b, 0x76, 0xfe, 0x9d, 0xe3, 0x93, 0x73, 0xfb, 0x3b, 0xe4, 0xf2, 0xf5,
	0xea, 0xdd, 0xa7, 0x87, 0xcf, 0x6f, 0x3e, 0xe6, 0x72, 0xae, 0xb4, 0x34, 0x92, 0x8e, 0x3f, 0xec,
	0xde, 0x6a, 0xc5, 0x57, 0x5a, 0x7e, 0x13, 0xdc, 0xcc, 0x7e, 0x76, 0x9a, 0x3b, 0x8f, 0x6b, 0xb1,
	0xdb, 0x8b, 0xca, 0xd0, 0x1b, 0xd2, 0x13, 0x3b, 0x65, 0xf2, 0x84, 0x75, 0xa6, 0x9d, 0xdb, 0xc1,
	0x1a, 0x89, 0x5e, 0x91, 0x6e, 0x95, 0xea, 0x3c, 0x61, 0x67, 0xd6, 0xec, 0x80, 0x32, 0xd2, 0x2f,
	0x8f, 0x52, 0x89, 0x52, 0xb2, 0xc8, 0xda, 0x3d, 0xc2, 0xfd, 0x42, 0xc2, 0x67, 0xce, 0xdd, 0x7d,
	0x0b, 0xf4, 0x39, 0xb9, 0xa8, 0x84, 0x3e, 0x08, 0x9d, 0x2b, 0xd6, 0xb5, 0x8e, 0x9a, 0x67, 0xbf,
	0x22, 0x32, 0x09, 0xca, 0x51, 0xc5, 0x09, 0x3e, 0x62, 0xf4, 0xb1, 0xae, 0xc5, 0x01, 0x94, 0x68,
	0x4e, 0x4a, 0xd4, 0xb5, 0x20, 0x41, 0x31, 0xda, 0x94, 0x5c, 0x26, 0xc2, 0x17, 0x83, 0x88, 0x9e,
	0xad, 0xa8, 0x52, 0x2c, 0xc7, 0x63, 0xd0, 0x6e, 0xb7, 0xd5, 0x2e, 0x23, 0x7d, 0x38, 0x25, 0x15,
	0x67, 0x3d, 0x17, 0x81, 0x08, 0x2d, 0xc0, 0x91, 0xc7, 0x46, 0xb0, 0xbe, 0x6b, 0xc1, 0x33, 0xf8,
	0xb4, 0xe0, 0xb9, 0xad, 0xed, 0xc2, 0xf9, 0x3c, 0xfb, 0xb8, 0xca, 0xc4, 0x86, 0x0d, 0x9a, 0x38,
	0x60, 0x3a, 0x25, 0x43, 0x7f, 0x86, 0x8c, 0xc4, 0xba, 0x43, 0x93, 0x8f, 0xde, 0x42, 0x73, 0xc3,
	0x26, 0x1a, 0x18, 0x7a, 0xa8, 0x52, 0xcd, 0x4b, 0xc3, 0x46, 0xae, 0x07, 0x47, 0x74, 0x41, 0xba,
	0x32, 0xd6, 0xa7, 0x05, 0x1b, 0x4f, 0xa3, 0xdb, 0xe1, 0xf2, 0xc5, 0xbc, 0xb5, 0xfe, 0xb9, 0x9f,
	0xb5, 0x7c, 0x8c, 0x17, 0x6b, 0x77, 0xd3, 0x8e, 0x43, 0xeb, 0x6d, 0x95, 0xb2, 0x09, 0x8e, 0xc3,
	0xd2, 0x6c, 0x4f, 0x46, 0xe1, 0xf5, 0x46, 0x0d, 0x9d, 0x50, 0x0d, 0x2f, 0xc9, 0xa0, 0xca, 0x4c,
	0xac, 0x4f, 0x50, 0x8b, 0xdb, 0x4d, 0x63, 0xf0, 0xe5, 0x2c, 0x59, 0xf4, 0xaf, 0x72, 0x96, 0xae,
	0x9c, 0xe5, 0xec, 0x4f, 0xb7, 0x95, 0x77, 0x69, 0xf3, 0x66, 0x26, 0xc8, 0x9b, 0xe1, 0xb2, 0xaa,
	0xcc, 0x4d, 0xd6, 0x65, 0xf5, 0xd8, 0xa8, 0x30, 0x0a, 0x55, 0x08, 0x03, 0x53, 0x45, 0x23, 0x4e,
	0x24, 0x58, 0x43, 0x79, 0xd4, 0x72, 0x6f, 0x84, 0xdd, 0xae, 0x53, 0x44, 0x68, 0x82, 0x0e, 0x11,
	0xf3, 0x04, 0x85, 0xd1, 0x18, 0xe8, 0x2b, 0x42, 0x10, 0x0e, 0x42, 0xa3, 0x38, 0x02, 0x0b, 0xd4,
	0xc9, 0xb5, 0x7b, 0x2d, 0x4e, 0x1d, 0x1e, 0xc3, 0x77, 0x34, 0x68, 0xbf, 0x23, 0xef, 0xc9, 0x13,
	0x94, 0x85, 0x47, 0x90, 0x84, 0x3d, 0x42, 0x2e, 0x94, 0x84, 0xe7, 0xda, 0x07, 0x6a, 0x1a, 0x05,
	0x3e, 0x94, 0x52, 0x79, 0x54, 0x42, 0x15, 0x87, 0x82, 0x8d, 0xbd, 0xcf, 0x31, 0x76, 0xe0, 0x25,
	0x3c, 0xa9, 0x3b, 0x08, 0x44, 0x5c, 0x1e, 0x95, 0x96, 0x3c, 0x4f, 0xd8, 0x7f, 0x75, 0xac, 0x65,
	0x98, 0x8d, 0xd2, 0x32, 0xd9, 0x73, 0x18, 0xec, 0xa5, 0x9b, 0x4d, 0x6d, 0xb0, 0xca, 0xe2, 0xf6,
	0x6d, 0xfe, 0x8f, 0xca, 0xb2, 0x44, 0x29, 0x39, 0xdf, 0x97, 0xb9, 0x61, 0xd4, 0x5a, 0xed, 0xb9,
	0x51, 0xd7, 0x93, 0x50, 0x5d, 0xb0, 0xb5, 0xcc, 0x80, 0xb4, 0xae, 0x70, 0x6b, 0x96, 0x20, 0xef,
	0x56, 0x1e, 0x44, 0x5e, 0x6e, 0x8a, 0x94, 0x5d, 0xbb, 0xbc, 0xb5, 0xc1, 0x46, 0x15, 0xd2, 0x94,
	0x92, 0xdd, 0x60, 0x94, 0x25, 0xfb, 0x27, 0xca, 0xe4, 0x8f, 0x4d, 0x11, 0xa7, 0xec, 0x29, 0xfe,
	0x89, 0x90, 0x21, 0x66, 0x13, 0x7f, 0x87, 0x09, 0x30, 0x17, 0xe3, 0xc8, 0x3e, 0x42, 0xad, 0xdc,
	0xd7, 0x9e, 0xe1, 0x23, 0x44, 0xbe, 0xbf, 0x23, 0xd7, 0xb9, 0x9c, 0xa7, 0x5a, 0xf1, 0xb6, 0xae,
	0xef, 0x69, 0x0b, 0x57, 0xf0, 0x23, 0x5e, 0x75, 0x7e, 0x9f, 0x45, 0x0f, 0xef, 0xbf, 0x7c, 0xed,
	0xd9, 0xff, 0xf2, 0xdd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x81, 0xa7, 0x70, 0xab, 0x05,
	0x00, 0x00,
}
