// Code generated by protoc-gen-go. DO NOT EDIT.
// source: APLPRDBMio.proto

package MqGrpcProject

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type APLPRDBM_Request struct {
	Productid            string   `protobuf:"bytes,1,opt,name=productid,proto3" json:"productid,omitempty"`
	Eccode               string   `protobuf:"bytes,2,opt,name=eccode,proto3" json:"eccode,omitempty"`
	Routecate            string   `protobuf:"bytes,3,opt,name=routecate,proto3" json:"routecate,omitempty"`
	Routeid              string   `protobuf:"bytes,4,opt,name=routeid,proto3" json:"routeid,omitempty"`
	Routever             string   `protobuf:"bytes,5,opt,name=routever,proto3" json:"routever,omitempty"`
	Opeid                string   `protobuf:"bytes,6,opt,name=opeid,proto3" json:"opeid,omitempty"`
	Opever               string   `protobuf:"bytes,7,opt,name=opever,proto3" json:"opever,omitempty"`
	Resveqptid           string   `protobuf:"bytes,8,opt,name=resveqptid,proto3" json:"resveqptid,omitempty"`
	Lotid                string   `protobuf:"bytes,9,opt,name=lotid,proto3" json:"lotid,omitempty"`
	Nxopeno              string   `protobuf:"bytes,10,opt,name=nxopeno,proto3" json:"nxopeno,omitempty"`
	Userecycleflag       string   `protobuf:"bytes,11,opt,name=userecycleflag,proto3" json:"userecycleflag,omitempty"`
	Moveoutlenght        string   `protobuf:"bytes,12,opt,name=moveoutlenght,proto3" json:"moveoutlenght,omitempty"`
	Serverip             string   `protobuf:"bytes,13,opt,name=serverip,proto3" json:"serverip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APLPRDBM_Request) Reset()         { *m = APLPRDBM_Request{} }
func (m *APLPRDBM_Request) String() string { return proto.CompactTextString(m) }
func (*APLPRDBM_Request) ProtoMessage()    {}
func (*APLPRDBM_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_402b1d763164fc95, []int{0}
}

func (m *APLPRDBM_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APLPRDBM_Request.Unmarshal(m, b)
}
func (m *APLPRDBM_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APLPRDBM_Request.Marshal(b, m, deterministic)
}
func (m *APLPRDBM_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APLPRDBM_Request.Merge(m, src)
}
func (m *APLPRDBM_Request) XXX_Size() int {
	return xxx_messageInfo_APLPRDBM_Request.Size(m)
}
func (m *APLPRDBM_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_APLPRDBM_Request.DiscardUnknown(m)
}

var xxx_messageInfo_APLPRDBM_Request proto.InternalMessageInfo

func (m *APLPRDBM_Request) GetProductid() string {
	if m != nil {
		return m.Productid
	}
	return ""
}

func (m *APLPRDBM_Request) GetEccode() string {
	if m != nil {
		return m.Eccode
	}
	return ""
}

func (m *APLPRDBM_Request) GetRoutecate() string {
	if m != nil {
		return m.Routecate
	}
	return ""
}

func (m *APLPRDBM_Request) GetRouteid() string {
	if m != nil {
		return m.Routeid
	}
	return ""
}

func (m *APLPRDBM_Request) GetRoutever() string {
	if m != nil {
		return m.Routever
	}
	return ""
}

func (m *APLPRDBM_Request) GetOpeid() string {
	if m != nil {
		return m.Opeid
	}
	return ""
}

func (m *APLPRDBM_Request) GetOpever() string {
	if m != nil {
		return m.Opever
	}
	return ""
}

func (m *APLPRDBM_Request) GetResveqptid() string {
	if m != nil {
		return m.Resveqptid
	}
	return ""
}

func (m *APLPRDBM_Request) GetLotid() string {
	if m != nil {
		return m.Lotid
	}
	return ""
}

func (m *APLPRDBM_Request) GetNxopeno() string {
	if m != nil {
		return m.Nxopeno
	}
	return ""
}

func (m *APLPRDBM_Request) GetUserecycleflag() string {
	if m != nil {
		return m.Userecycleflag
	}
	return ""
}

func (m *APLPRDBM_Request) GetMoveoutlenght() string {
	if m != nil {
		return m.Moveoutlenght
	}
	return ""
}

func (m *APLPRDBM_Request) GetServerip() string {
	if m != nil {
		return m.Serverip
	}
	return ""
}

type APLPRDBM_Reply struct {
	Trxid                string         `protobuf:"bytes,1,opt,name=trxid,proto3" json:"trxid,omitempty"`
	Typeid               string         `protobuf:"bytes,2,opt,name=typeid,proto3" json:"typeid,omitempty"`
	Rtncode              string         `protobuf:"bytes,3,opt,name=rtncode,proto3" json:"rtncode,omitempty"`
	Rtnmesg              string         `protobuf:"bytes,4,opt,name=rtnmesg,proto3" json:"rtnmesg,omitempty"`
	Productid            string         `protobuf:"bytes,5,opt,name=productid,proto3" json:"productid,omitempty"`
	Eccode               string         `protobuf:"bytes,6,opt,name=eccode,proto3" json:"eccode,omitempty"`
	Routeid              string         `protobuf:"bytes,7,opt,name=routeid,proto3" json:"routeid,omitempty"`
	Routever             string         `protobuf:"bytes,8,opt,name=routever,proto3" json:"routever,omitempty"`
	Bomcnt               string         `protobuf:"bytes,9,opt,name=bomcnt,proto3" json:"bomcnt,omitempty"`
	Oary1                []*APLPRDBMoA1 `protobuf:"bytes,10,rep,name=oary1,proto3" json:"oary1,omitempty"`
	Errmsg               string         `protobuf:"bytes,11,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *APLPRDBM_Reply) Reset()         { *m = APLPRDBM_Reply{} }
func (m *APLPRDBM_Reply) String() string { return proto.CompactTextString(m) }
func (*APLPRDBM_Reply) ProtoMessage()    {}
func (*APLPRDBM_Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_402b1d763164fc95, []int{1}
}

func (m *APLPRDBM_Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APLPRDBM_Reply.Unmarshal(m, b)
}
func (m *APLPRDBM_Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APLPRDBM_Reply.Marshal(b, m, deterministic)
}
func (m *APLPRDBM_Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APLPRDBM_Reply.Merge(m, src)
}
func (m *APLPRDBM_Reply) XXX_Size() int {
	return xxx_messageInfo_APLPRDBM_Reply.Size(m)
}
func (m *APLPRDBM_Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_APLPRDBM_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_APLPRDBM_Reply proto.InternalMessageInfo

func (m *APLPRDBM_Reply) GetTrxid() string {
	if m != nil {
		return m.Trxid
	}
	return ""
}

func (m *APLPRDBM_Reply) GetTypeid() string {
	if m != nil {
		return m.Typeid
	}
	return ""
}

func (m *APLPRDBM_Reply) GetRtncode() string {
	if m != nil {
		return m.Rtncode
	}
	return ""
}

func (m *APLPRDBM_Reply) GetRtnmesg() string {
	if m != nil {
		return m.Rtnmesg
	}
	return ""
}

func (m *APLPRDBM_Reply) GetProductid() string {
	if m != nil {
		return m.Productid
	}
	return ""
}

func (m *APLPRDBM_Reply) GetEccode() string {
	if m != nil {
		return m.Eccode
	}
	return ""
}

func (m *APLPRDBM_Reply) GetRouteid() string {
	if m != nil {
		return m.Routeid
	}
	return ""
}

func (m *APLPRDBM_Reply) GetRoutever() string {
	if m != nil {
		return m.Routever
	}
	return ""
}

func (m *APLPRDBM_Reply) GetBomcnt() string {
	if m != nil {
		return m.Bomcnt
	}
	return ""
}

func (m *APLPRDBM_Reply) GetOary1() []*APLPRDBMoA1 {
	if m != nil {
		return m.Oary1
	}
	return nil
}

func (m *APLPRDBM_Reply) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type APLPRDBMoA1 struct {
	Opever               string         `protobuf:"bytes,1,opt,name=opever,proto3" json:"opever,omitempty"`
	Bomid                string         `protobuf:"bytes,2,opt,name=bomid,proto3" json:"bomid,omitempty"`
	Bomdsc               string         `protobuf:"bytes,3,opt,name=bomdsc,proto3" json:"bomdsc,omitempty"`
	Stageid              string         `protobuf:"bytes,4,opt,name=stageid,proto3" json:"stageid,omitempty"`
	Addtinfo1            string         `protobuf:"bytes,5,opt,name=addtinfo1,proto3" json:"addtinfo1,omitempty"`
	Addtinfo2            string         `protobuf:"bytes,6,opt,name=addtinfo2,proto3" json:"addtinfo2,omitempty"`
	Addtinfo3            string         `protobuf:"bytes,7,opt,name=addtinfo3,proto3" json:"addtinfo3,omitempty"`
	Mtrlcnt              string         `protobuf:"bytes,8,opt,name=mtrlcnt,proto3" json:"mtrlcnt,omitempty"`
	Oary2                []*APLPRDBMoA2 `protobuf:"bytes,9,rep,name=oary2,proto3" json:"oary2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *APLPRDBMoA1) Reset()         { *m = APLPRDBMoA1{} }
func (m *APLPRDBMoA1) String() string { return proto.CompactTextString(m) }
func (*APLPRDBMoA1) ProtoMessage()    {}
func (*APLPRDBMoA1) Descriptor() ([]byte, []int) {
	return fileDescriptor_402b1d763164fc95, []int{2}
}

func (m *APLPRDBMoA1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APLPRDBMoA1.Unmarshal(m, b)
}
func (m *APLPRDBMoA1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APLPRDBMoA1.Marshal(b, m, deterministic)
}
func (m *APLPRDBMoA1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APLPRDBMoA1.Merge(m, src)
}
func (m *APLPRDBMoA1) XXX_Size() int {
	return xxx_messageInfo_APLPRDBMoA1.Size(m)
}
func (m *APLPRDBMoA1) XXX_DiscardUnknown() {
	xxx_messageInfo_APLPRDBMoA1.DiscardUnknown(m)
}

var xxx_messageInfo_APLPRDBMoA1 proto.InternalMessageInfo

func (m *APLPRDBMoA1) GetOpever() string {
	if m != nil {
		return m.Opever
	}
	return ""
}

func (m *APLPRDBMoA1) GetBomid() string {
	if m != nil {
		return m.Bomid
	}
	return ""
}

func (m *APLPRDBMoA1) GetBomdsc() string {
	if m != nil {
		return m.Bomdsc
	}
	return ""
}

func (m *APLPRDBMoA1) GetStageid() string {
	if m != nil {
		return m.Stageid
	}
	return ""
}

func (m *APLPRDBMoA1) GetAddtinfo1() string {
	if m != nil {
		return m.Addtinfo1
	}
	return ""
}

func (m *APLPRDBMoA1) GetAddtinfo2() string {
	if m != nil {
		return m.Addtinfo2
	}
	return ""
}

func (m *APLPRDBMoA1) GetAddtinfo3() string {
	if m != nil {
		return m.Addtinfo3
	}
	return ""
}

func (m *APLPRDBMoA1) GetMtrlcnt() string {
	if m != nil {
		return m.Mtrlcnt
	}
	return ""
}

func (m *APLPRDBMoA1) GetOary2() []*APLPRDBMoA2 {
	if m != nil {
		return m.Oary2
	}
	return nil
}

type APLPRDBMoA2 struct {
	Mtrlproductid        string   `protobuf:"bytes,1,opt,name=mtrlproductid,proto3" json:"mtrlproductid,omitempty"`
	Mtrlproductdsc       string   `protobuf:"bytes,2,opt,name=mtrlproductdsc,proto3" json:"mtrlproductdsc,omitempty"`
	Mtrlcate             string   `protobuf:"bytes,3,opt,name=mtrlcate,proto3" json:"mtrlcate,omitempty"`
	Planqty              string   `protobuf:"bytes,4,opt,name=planqty,proto3" json:"planqty,omitempty"`
	Mtrlunit             string   `protobuf:"bytes,5,opt,name=mtrlunit,proto3" json:"mtrlunit,omitempty"`
	Spcfymtrllotid       string   `protobuf:"bytes,6,opt,name=spcfymtrllotid,proto3" json:"spcfymtrllotid,omitempty"`
	Ext_1                string   `protobuf:"bytes,7,opt,name=ext_1,json=ext1,proto3" json:"ext_1,omitempty"`
	Ext_2                string   `protobuf:"bytes,8,opt,name=ext_2,json=ext2,proto3" json:"ext_2,omitempty"`
	Ext_3                string   `protobuf:"bytes,9,opt,name=ext_3,json=ext3,proto3" json:"ext_3,omitempty"`
	Ext_4                string   `protobuf:"bytes,10,opt,name=ext_4,json=ext4,proto3" json:"ext_4,omitempty"`
	Ext_5                string   `protobuf:"bytes,11,opt,name=ext_5,json=ext5,proto3" json:"ext_5,omitempty"`
	Parentid             string   `protobuf:"bytes,12,opt,name=parentid,proto3" json:"parentid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APLPRDBMoA2) Reset()         { *m = APLPRDBMoA2{} }
func (m *APLPRDBMoA2) String() string { return proto.CompactTextString(m) }
func (*APLPRDBMoA2) ProtoMessage()    {}
func (*APLPRDBMoA2) Descriptor() ([]byte, []int) {
	return fileDescriptor_402b1d763164fc95, []int{3}
}

func (m *APLPRDBMoA2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APLPRDBMoA2.Unmarshal(m, b)
}
func (m *APLPRDBMoA2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APLPRDBMoA2.Marshal(b, m, deterministic)
}
func (m *APLPRDBMoA2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APLPRDBMoA2.Merge(m, src)
}
func (m *APLPRDBMoA2) XXX_Size() int {
	return xxx_messageInfo_APLPRDBMoA2.Size(m)
}
func (m *APLPRDBMoA2) XXX_DiscardUnknown() {
	xxx_messageInfo_APLPRDBMoA2.DiscardUnknown(m)
}

var xxx_messageInfo_APLPRDBMoA2 proto.InternalMessageInfo

func (m *APLPRDBMoA2) GetMtrlproductid() string {
	if m != nil {
		return m.Mtrlproductid
	}
	return ""
}

func (m *APLPRDBMoA2) GetMtrlproductdsc() string {
	if m != nil {
		return m.Mtrlproductdsc
	}
	return ""
}

func (m *APLPRDBMoA2) GetMtrlcate() string {
	if m != nil {
		return m.Mtrlcate
	}
	return ""
}

func (m *APLPRDBMoA2) GetPlanqty() string {
	if m != nil {
		return m.Planqty
	}
	return ""
}

func (m *APLPRDBMoA2) GetMtrlunit() string {
	if m != nil {
		return m.Mtrlunit
	}
	return ""
}

func (m *APLPRDBMoA2) GetSpcfymtrllotid() string {
	if m != nil {
		return m.Spcfymtrllotid
	}
	return ""
}

func (m *APLPRDBMoA2) GetExt_1() string {
	if m != nil {
		return m.Ext_1
	}
	return ""
}

func (m *APLPRDBMoA2) GetExt_2() string {
	if m != nil {
		return m.Ext_2
	}
	return ""
}

func (m *APLPRDBMoA2) GetExt_3() string {
	if m != nil {
		return m.Ext_3
	}
	return ""
}

func (m *APLPRDBMoA2) GetExt_4() string {
	if m != nil {
		return m.Ext_4
	}
	return ""
}

func (m *APLPRDBMoA2) GetExt_5() string {
	if m != nil {
		return m.Ext_5
	}
	return ""
}

func (m *APLPRDBMoA2) GetParentid() string {
	if m != nil {
		return m.Parentid
	}
	return ""
}

func init() {
	proto.RegisterType((*APLPRDBM_Request)(nil), "MqGrpcProject.APLPRDBM_Request")
	proto.RegisterType((*APLPRDBM_Reply)(nil), "MqGrpcProject.APLPRDBM_Reply")
	proto.RegisterType((*APLPRDBMoA1)(nil), "MqGrpcProject.APLPRDBMo_a1")
	proto.RegisterType((*APLPRDBMoA2)(nil), "MqGrpcProject.APLPRDBMo_a2")
}

func init() { proto.RegisterFile("APLPRDBMio.proto", fileDescriptor_402b1d763164fc95) }

var fileDescriptor_402b1d763164fc95 = []byte{
	// 610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x5f, 0x6a, 0xdb, 0x4c,
	0x14, 0xc5, 0xb1, 0x1d, 0x39, 0xf1, 0x24, 0x0e, 0x1f, 0xf3, 0xa5, 0x61, 0x68, 0x4b, 0x09, 0xa6,
	0x94, 0x3c, 0x19, 0x24, 0x27, 0x0b, 0xa8, 0x29, 0xb4, 0x0f, 0x09, 0x18, 0xbf, 0xf4, 0xd1, 0xc8,
	0xa3, 0x6b, 0x57, 0x45, 0xd2, 0x8c, 0x47, 0x23, 0x63, 0xbd, 0x77, 0x0b, 0xdd, 0x40, 0x77, 0xd2,
	0x75, 0x74, 0x33, 0xe5, 0xce, 0x1f, 0x59, 0x32, 0x84, 0xbe, 0xe9, 0x9c, 0x3b, 0x23, 0xdd, 0xf9,
	0x9d, 0x3b, 0x22, 0xff, 0x7d, 0x5c, 0x3c, 0x2d, 0x96, 0x9f, 0xe6, 0xcf, 0xa9, 0x98, 0x4a, 0x25,
	0xb4, 0xa0, 0xe3, 0xe7, 0xdd, 0x67, 0x25, 0xf9, 0x42, 0x89, 0xef, 0xc0, 0xf5, 0xe4, 0xc7, 0xe0,
	0xb8, 0x66, 0xb5, 0x84, 0x5d, 0x05, 0xa5, 0xa6, 0x6f, 0xc9, 0x48, 0x2a, 0x91, 0x54, 0x5c, 0xa7,
	0x09, 0xeb, 0xdd, 0xf5, 0xee, 0x47, 0xcb, 0xa3, 0x41, 0x6f, 0xc9, 0x10, 0x38, 0x17, 0x09, 0xb0,
	0xbe, 0x29, 0x39, 0x85, 0xbb, 0x94, 0xa8, 0x34, 0xf0, 0x58, 0x03, 0x1b, 0xd8, 0x5d, 0x8d, 0x41,
	0x19, 0x39, 0x37, 0x22, 0x4d, 0xd8, 0x99, 0xa9, 0x79, 0x49, 0x5f, 0x93, 0x0b, 0xf3, 0xb8, 0x07,
	0xc5, 0x02, 0x53, 0x6a, 0x34, 0xbd, 0x21, 0x81, 0x90, 0xb8, 0x67, 0x68, 0x0a, 0x56, 0x60, 0x07,
	0x42, 0x9a, 0xf5, 0xe7, 0xb6, 0x03, 0xab, 0xe8, 0x3b, 0x42, 0x14, 0x94, 0x7b, 0xd8, 0x49, 0x6c,
	0xfc, 0xc2, 0xd4, 0x5a, 0x0e, 0xbe, 0x2d, 0x13, 0x58, 0x1a, 0xd9, 0xb7, 0x19, 0x81, 0x9d, 0x15,
	0x07, 0x21, 0xa1, 0x10, 0x8c, 0xd8, 0xce, 0x9c, 0xa4, 0x1f, 0xc8, 0x75, 0x55, 0x82, 0x02, 0x5e,
	0xf3, 0x0c, 0x36, 0x59, 0xbc, 0x65, 0x97, 0x66, 0xc1, 0x89, 0x4b, 0xdf, 0x93, 0x71, 0x2e, 0xf6,
	0x20, 0x2a, 0x9d, 0x41, 0xb1, 0xfd, 0xa6, 0xd9, 0x95, 0x59, 0xd6, 0x35, 0xf1, 0x9c, 0x25, 0xa8,
	0x3d, 0xa8, 0x54, 0xb2, 0xb1, 0x3d, 0xa7, 0xd7, 0x93, 0xdf, 0x7d, 0x72, 0xdd, 0x8a, 0x41, 0x66,
	0x35, 0x36, 0xab, 0xd5, 0xa1, 0x09, 0xc0, 0x0a, 0x3c, 0xba, 0xae, 0x0d, 0x11, 0x07, 0xdf, 0x2a,
	0x83, 0x57, 0x17, 0x26, 0x95, 0x81, 0xc3, 0x6b, 0xa5, 0xab, 0xe4, 0x50, 0x6e, 0x1b, 0xf0, 0x56,
	0x76, 0x63, 0x0e, 0x5e, 0x8e, 0x79, 0xd8, 0x89, 0xb9, 0x15, 0xe4, 0xf9, 0xcb, 0x41, 0x5e, 0x9c,
	0x04, 0x79, 0x4b, 0x86, 0x6b, 0x91, 0xf3, 0x42, 0x3b, 0xf6, 0x4e, 0xd1, 0x90, 0x04, 0x22, 0x56,
	0x75, 0xc8, 0xc8, 0xdd, 0xe0, 0xfe, 0x32, 0x7a, 0x33, 0xed, 0x8c, 0xe7, 0xd4, 0x33, 0x11, 0xab,
	0x38, 0x5c, 0xda, 0x95, 0xa6, 0x31, 0xa5, 0xf2, 0xd2, 0xa7, 0xe1, 0xd4, 0xe4, 0x67, 0x9f, 0x5c,
	0xb5, 0xd7, 0xb7, 0xc6, 0xa4, 0xd7, 0x19, 0x93, 0x1b, 0x12, 0xac, 0x45, 0xde, 0x20, 0xb4, 0xc2,
	0x75, 0x98, 0x94, 0xdc, 0x01, 0x74, 0x0a, 0xcf, 0x5b, 0xea, 0x78, 0xdb, 0x1a, 0x5c, 0x27, 0x91,
	0x5f, 0x9c, 0x24, 0x3a, 0x2d, 0x36, 0x22, 0xf4, 0xfc, 0x1a, 0xa3, 0x5d, 0x8d, 0x1c, 0xc2, 0xa3,
	0xd1, 0xae, 0xce, 0x1c, 0xc7, 0xa3, 0x81, 0xdf, 0xcc, 0xb5, 0xca, 0x10, 0x97, 0x05, 0xe9, 0xa5,
	0xe7, 0x15, 0xb1, 0xd1, 0xbf, 0x78, 0x45, 0x96, 0x57, 0x34, 0xf9, 0xd3, 0xe5, 0x12, 0x99, 0x71,
	0xd5, 0x2a, 0x3b, 0xbd, 0xe2, 0x5d, 0x13, 0x87, 0xbf, 0x65, 0x20, 0x17, 0x8b, 0xeb, 0xc4, 0xc5,
	0xd4, 0x4d, 0x73, 0xc7, 0x5b, 0xdf, 0x68, 0x3c, 0x87, 0xcc, 0xe2, 0x62, 0xa7, 0x6b, 0xcf, 0xce,
	0x49, 0xbf, 0xab, 0x2a, 0x52, 0xed, 0x2f, 0xbd, 0xd7, 0xf8, 0xe5, 0x52, 0xf2, 0x4d, 0x8d, 0x86,
	0xbd, 0xaf, 0x16, 0xdf, 0x89, 0x4b, 0xff, 0x27, 0x01, 0x1c, 0xf4, 0x2a, 0x74, 0xfc, 0xce, 0xe0,
	0xa0, 0x43, 0x6f, 0x46, 0x0e, 0x1c, 0x9a, 0x91, 0x37, 0x67, 0x6e, 0xf8, 0xd0, 0x9c, 0x79, 0xf3,
	0xc1, 0xdd, 0x7a, 0x34, 0x1f, 0xbc, 0xf9, 0xe8, 0x66, 0x0b, 0xcd, 0x47, 0x6c, 0x56, 0xc6, 0x0a,
	0x0a, 0x6c, 0xc5, 0x5e, 0xed, 0x46, 0xcf, 0x67, 0xe4, 0x55, 0x2a, 0xa6, 0x5b, 0x25, 0x79, 0x37,
	0x8a, 0x39, 0xed, 0xc8, 0x05, 0xfe, 0x7c, 0x17, 0xbd, 0x5f, 0xfd, 0xc1, 0x97, 0xa7, 0xaf, 0xeb,
	0xa1, 0xf9, 0x17, 0xcf, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xf7, 0x64, 0x6b, 0x9f, 0x05,
	0x00, 0x00,
}
