// Code generated by protoc-gen-go. DO NOT EDIT.
// source: APLRSVPRio.proto

package MqGrpcProject

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type APLRSVPR_Request struct {
	Bayid                string   `protobuf:"bytes,1,opt,name=bayid,proto3" json:"bayid,omitempty"`
	Resveqptid           string   `protobuf:"bytes,2,opt,name=resveqptid,proto3" json:"resveqptid,omitempty"`
	Resvdate             string   `protobuf:"bytes,3,opt,name=resvdate,proto3" json:"resvdate,omitempty"`
	Resvshiftseq         string   `protobuf:"bytes,4,opt,name=resvshiftseq,proto3" json:"resvshiftseq,omitempty"`
	Prepstartdate        string   `protobuf:"bytes,5,opt,name=prepstartdate,proto3" json:"prepstartdate,omitempty"`
	Prependdate          string   `protobuf:"bytes,6,opt,name=prependdate,proto3" json:"prependdate,omitempty"`
	Preptype             string   `protobuf:"bytes,7,opt,name=preptype,proto3" json:"preptype,omitempty"`
	Lotid                string   `protobuf:"bytes,8,opt,name=lotid,proto3" json:"lotid,omitempty"`
	Onlyoutsideflg       string   `protobuf:"bytes,9,opt,name=onlyoutsideflg,proto3" json:"onlyoutsideflg,omitempty"`
	Needorderflg         string   `protobuf:"bytes,10,opt,name=needorderflg,proto3" json:"needorderflg,omitempty"`
	Serverip             string   `protobuf:"bytes,11,opt,name=serverip,proto3" json:"serverip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APLRSVPR_Request) Reset()         { *m = APLRSVPR_Request{} }
func (m *APLRSVPR_Request) String() string { return proto.CompactTextString(m) }
func (*APLRSVPR_Request) ProtoMessage()    {}
func (*APLRSVPR_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_42803677346be111, []int{0}
}

func (m *APLRSVPR_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APLRSVPR_Request.Unmarshal(m, b)
}
func (m *APLRSVPR_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APLRSVPR_Request.Marshal(b, m, deterministic)
}
func (m *APLRSVPR_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APLRSVPR_Request.Merge(m, src)
}
func (m *APLRSVPR_Request) XXX_Size() int {
	return xxx_messageInfo_APLRSVPR_Request.Size(m)
}
func (m *APLRSVPR_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_APLRSVPR_Request.DiscardUnknown(m)
}

var xxx_messageInfo_APLRSVPR_Request proto.InternalMessageInfo

func (m *APLRSVPR_Request) GetBayid() string {
	if m != nil {
		return m.Bayid
	}
	return ""
}

func (m *APLRSVPR_Request) GetResveqptid() string {
	if m != nil {
		return m.Resveqptid
	}
	return ""
}

func (m *APLRSVPR_Request) GetResvdate() string {
	if m != nil {
		return m.Resvdate
	}
	return ""
}

func (m *APLRSVPR_Request) GetResvshiftseq() string {
	if m != nil {
		return m.Resvshiftseq
	}
	return ""
}

func (m *APLRSVPR_Request) GetPrepstartdate() string {
	if m != nil {
		return m.Prepstartdate
	}
	return ""
}

func (m *APLRSVPR_Request) GetPrependdate() string {
	if m != nil {
		return m.Prependdate
	}
	return ""
}

func (m *APLRSVPR_Request) GetPreptype() string {
	if m != nil {
		return m.Preptype
	}
	return ""
}

func (m *APLRSVPR_Request) GetLotid() string {
	if m != nil {
		return m.Lotid
	}
	return ""
}

func (m *APLRSVPR_Request) GetOnlyoutsideflg() string {
	if m != nil {
		return m.Onlyoutsideflg
	}
	return ""
}

func (m *APLRSVPR_Request) GetNeedorderflg() string {
	if m != nil {
		return m.Needorderflg
	}
	return ""
}

func (m *APLRSVPR_Request) GetServerip() string {
	if m != nil {
		return m.Serverip
	}
	return ""
}

type APLRSVPR_Reply struct {
	Trxid                string        `protobuf:"bytes,1,opt,name=trxid,proto3" json:"trxid,omitempty"`
	Typeid               string        `protobuf:"bytes,2,opt,name=typeid,proto3" json:"typeid,omitempty"`
	Rtncode              string        `protobuf:"bytes,3,opt,name=rtncode,proto3" json:"rtncode,omitempty"`
	Rtnmesg              string        `protobuf:"bytes,4,opt,name=rtnmesg,proto3" json:"rtnmesg,omitempty"`
	Lotarycnt            string        `protobuf:"bytes,5,opt,name=lotarycnt,proto3" json:"lotarycnt,omitempty"`
	Oary                 []*APLRSVPRoA `protobuf:"bytes,6,rep,name=oary,proto3" json:"oary,omitempty"`
	Errmsg               string        `protobuf:"bytes,7,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *APLRSVPR_Reply) Reset()         { *m = APLRSVPR_Reply{} }
func (m *APLRSVPR_Reply) String() string { return proto.CompactTextString(m) }
func (*APLRSVPR_Reply) ProtoMessage()    {}
func (*APLRSVPR_Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_42803677346be111, []int{1}
}

func (m *APLRSVPR_Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APLRSVPR_Reply.Unmarshal(m, b)
}
func (m *APLRSVPR_Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APLRSVPR_Reply.Marshal(b, m, deterministic)
}
func (m *APLRSVPR_Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APLRSVPR_Reply.Merge(m, src)
}
func (m *APLRSVPR_Reply) XXX_Size() int {
	return xxx_messageInfo_APLRSVPR_Reply.Size(m)
}
func (m *APLRSVPR_Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_APLRSVPR_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_APLRSVPR_Reply proto.InternalMessageInfo

func (m *APLRSVPR_Reply) GetTrxid() string {
	if m != nil {
		return m.Trxid
	}
	return ""
}

func (m *APLRSVPR_Reply) GetTypeid() string {
	if m != nil {
		return m.Typeid
	}
	return ""
}

func (m *APLRSVPR_Reply) GetRtncode() string {
	if m != nil {
		return m.Rtncode
	}
	return ""
}

func (m *APLRSVPR_Reply) GetRtnmesg() string {
	if m != nil {
		return m.Rtnmesg
	}
	return ""
}

func (m *APLRSVPR_Reply) GetLotarycnt() string {
	if m != nil {
		return m.Lotarycnt
	}
	return ""
}

func (m *APLRSVPR_Reply) GetOary() []*APLRSVPRoA {
	if m != nil {
		return m.Oary
	}
	return nil
}

func (m *APLRSVPR_Reply) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type APLRSVPRoA struct {
	Lotid                string   `protobuf:"bytes,1,opt,name=lotid,proto3" json:"lotid,omitempty"`
	Lotstat              string   `protobuf:"bytes,2,opt,name=lotstat,proto3" json:"lotstat,omitempty"`
	Nxopeno              string   `protobuf:"bytes,3,opt,name=nxopeno,proto3" json:"nxopeno,omitempty"`
	Mtrlproductid        string   `protobuf:"bytes,4,opt,name=mtrlproductid,proto3" json:"mtrlproductid,omitempty"`
	Preptype             string   `protobuf:"bytes,5,opt,name=preptype,proto3" json:"preptype,omitempty"`
	Prepstat             string   `protobuf:"bytes,6,opt,name=prepstat,proto3" json:"prepstat,omitempty"`
	Prepdate             string   `protobuf:"bytes,7,opt,name=prepdate,proto3" json:"prepdate,omitempty"`
	Prepseqno            string   `protobuf:"bytes,8,opt,name=prepseqno,proto3" json:"prepseqno,omitempty"`
	Resvdate             string   `protobuf:"bytes,9,opt,name=resvdate,proto3" json:"resvdate,omitempty"`
	Resvshiftseq         string   `protobuf:"bytes,10,opt,name=resvshiftseq,proto3" json:"resvshiftseq,omitempty"`
	Routeid              string   `protobuf:"bytes,11,opt,name=routeid,proto3" json:"routeid,omitempty"`
	Routever             string   `protobuf:"bytes,12,opt,name=routever,proto3" json:"routever,omitempty"`
	Claimdate            string   `protobuf:"bytes,13,opt,name=claimdate,proto3" json:"claimdate,omitempty"`
	Claimtime            string   `protobuf:"bytes,14,opt,name=claimtime,proto3" json:"claimtime,omitempty"`
	Claimuser            string   `protobuf:"bytes,15,opt,name=claimuser,proto3" json:"claimuser,omitempty"`
	Nxopeid              string   `protobuf:"bytes,16,opt,name=nxopeid,proto3" json:"nxopeid,omitempty"`
	Nxopever             string   `protobuf:"bytes,17,opt,name=nxopever,proto3" json:"nxopever,omitempty"`
	Spltid               string   `protobuf:"bytes,18,opt,name=spltid,proto3" json:"spltid,omitempty"`
	Resveqptid           string   `protobuf:"bytes,19,opt,name=resveqptid,proto3" json:"resveqptid,omitempty"`
	Shtcnt               string   `protobuf:"bytes,20,opt,name=shtcnt,proto3" json:"shtcnt,omitempty"`
	Readyshtcnt          string   `protobuf:"bytes,21,opt,name=readyshtcnt,proto3" json:"readyshtcnt,omitempty"`
	Productid            string   `protobuf:"bytes,22,opt,name=productid,proto3" json:"productid,omitempty"`
	Eccode               string   `protobuf:"bytes,23,opt,name=eccode,proto3" json:"eccode,omitempty"`
	Mainrouteid          string   `protobuf:"bytes,24,opt,name=mainrouteid,proto3" json:"mainrouteid,omitempty"`
	Mainroutever         string   `protobuf:"bytes,25,opt,name=mainroutever,proto3" json:"mainroutever,omitempty"`
	Cropeno              string   `protobuf:"bytes,26,opt,name=cropeno,proto3" json:"cropeno,omitempty"`
	Lineid               string   `protobuf:"bytes,27,opt,name=lineid,proto3" json:"lineid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APLRSVPRoA) Reset()         { *m = APLRSVPRoA{} }
func (m *APLRSVPRoA) String() string { return proto.CompactTextString(m) }
func (*APLRSVPRoA) ProtoMessage()    {}
func (*APLRSVPRoA) Descriptor() ([]byte, []int) {
	return fileDescriptor_42803677346be111, []int{2}
}

func (m *APLRSVPRoA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APLRSVPRoA.Unmarshal(m, b)
}
func (m *APLRSVPRoA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APLRSVPRoA.Marshal(b, m, deterministic)
}
func (m *APLRSVPRoA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APLRSVPRoA.Merge(m, src)
}
func (m *APLRSVPRoA) XXX_Size() int {
	return xxx_messageInfo_APLRSVPRoA.Size(m)
}
func (m *APLRSVPRoA) XXX_DiscardUnknown() {
	xxx_messageInfo_APLRSVPRoA.DiscardUnknown(m)
}

var xxx_messageInfo_APLRSVPRoA proto.InternalMessageInfo

func (m *APLRSVPRoA) GetLotid() string {
	if m != nil {
		return m.Lotid
	}
	return ""
}

func (m *APLRSVPRoA) GetLotstat() string {
	if m != nil {
		return m.Lotstat
	}
	return ""
}

func (m *APLRSVPRoA) GetNxopeno() string {
	if m != nil {
		return m.Nxopeno
	}
	return ""
}

func (m *APLRSVPRoA) GetMtrlproductid() string {
	if m != nil {
		return m.Mtrlproductid
	}
	return ""
}

func (m *APLRSVPRoA) GetPreptype() string {
	if m != nil {
		return m.Preptype
	}
	return ""
}

func (m *APLRSVPRoA) GetPrepstat() string {
	if m != nil {
		return m.Prepstat
	}
	return ""
}

func (m *APLRSVPRoA) GetPrepdate() string {
	if m != nil {
		return m.Prepdate
	}
	return ""
}

func (m *APLRSVPRoA) GetPrepseqno() string {
	if m != nil {
		return m.Prepseqno
	}
	return ""
}

func (m *APLRSVPRoA) GetResvdate() string {
	if m != nil {
		return m.Resvdate
	}
	return ""
}

func (m *APLRSVPRoA) GetResvshiftseq() string {
	if m != nil {
		return m.Resvshiftseq
	}
	return ""
}

func (m *APLRSVPRoA) GetRouteid() string {
	if m != nil {
		return m.Routeid
	}
	return ""
}

func (m *APLRSVPRoA) GetRoutever() string {
	if m != nil {
		return m.Routever
	}
	return ""
}

func (m *APLRSVPRoA) GetClaimdate() string {
	if m != nil {
		return m.Claimdate
	}
	return ""
}

func (m *APLRSVPRoA) GetClaimtime() string {
	if m != nil {
		return m.Claimtime
	}
	return ""
}

func (m *APLRSVPRoA) GetClaimuser() string {
	if m != nil {
		return m.Claimuser
	}
	return ""
}

func (m *APLRSVPRoA) GetNxopeid() string {
	if m != nil {
		return m.Nxopeid
	}
	return ""
}

func (m *APLRSVPRoA) GetNxopever() string {
	if m != nil {
		return m.Nxopever
	}
	return ""
}

func (m *APLRSVPRoA) GetSpltid() string {
	if m != nil {
		return m.Spltid
	}
	return ""
}

func (m *APLRSVPRoA) GetResveqptid() string {
	if m != nil {
		return m.Resveqptid
	}
	return ""
}

func (m *APLRSVPRoA) GetShtcnt() string {
	if m != nil {
		return m.Shtcnt
	}
	return ""
}

func (m *APLRSVPRoA) GetReadyshtcnt() string {
	if m != nil {
		return m.Readyshtcnt
	}
	return ""
}

func (m *APLRSVPRoA) GetProductid() string {
	if m != nil {
		return m.Productid
	}
	return ""
}

func (m *APLRSVPRoA) GetEccode() string {
	if m != nil {
		return m.Eccode
	}
	return ""
}

func (m *APLRSVPRoA) GetMainrouteid() string {
	if m != nil {
		return m.Mainrouteid
	}
	return ""
}

func (m *APLRSVPRoA) GetMainroutever() string {
	if m != nil {
		return m.Mainroutever
	}
	return ""
}

func (m *APLRSVPRoA) GetCropeno() string {
	if m != nil {
		return m.Cropeno
	}
	return ""
}

func (m *APLRSVPRoA) GetLineid() string {
	if m != nil {
		return m.Lineid
	}
	return ""
}

func init() {
	proto.RegisterType((*APLRSVPR_Request)(nil), "MqGrpcProject.APLRSVPR_Request")
	proto.RegisterType((*APLRSVPR_Reply)(nil), "MqGrpcProject.APLRSVPR_Reply")
	proto.RegisterType((*APLRSVPRoA)(nil), "MqGrpcProject.APLRSVPRo_a")
}

func init() { proto.RegisterFile("APLRSVPRio.proto", fileDescriptor_42803677346be111) }

var fileDescriptor_42803677346be111 = []byte{
	// 633 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x56, 0xb7, 0x35, 0x5d, 0xdd, 0xb5, 0x0c, 0xb3, 0x0d, 0x53, 0x26, 0x54, 0x55, 0x08, 0xed,
	0xaa, 0x17, 0xec, 0x09, 0xd8, 0x0d, 0x5c, 0x0c, 0xa9, 0x2a, 0x12, 0x5c, 0x4e, 0x59, 0x72, 0xd6,
	0x19, 0x25, 0xb1, 0x6b, 0xbb, 0xd5, 0xf2, 0x20, 0xbc, 0x00, 0x4f, 0xc5, 0x33, 0xf0, 0x14, 0xe8,
	0xf8, 0x27, 0x71, 0x0a, 0x12, 0x77, 0xf9, 0xbe, 0xef, 0xc4, 0xe7, 0xef, 0xb3, 0xc9, 0xe9, 0x87,
	0xe5, 0xed, 0xea, 0xcb, 0xd7, 0xe5, 0x8a, 0x8b, 0x85, 0x54, 0xc2, 0x08, 0x3a, 0xfe, 0xbc, 0xf9,
	0xa8, 0x64, 0xb6, 0x54, 0xe2, 0x3b, 0x64, 0x66, 0xfe, 0xfb, 0xa0, 0x8d, 0xb9, 0x5b, 0xc1, 0x66,
	0x0b, 0xda, 0xd0, 0x33, 0xd2, 0xbf, 0x4f, 0x6b, 0x9e, 0xb3, 0xde, 0xac, 0x77, 0x35, 0x5c, 0x39,
	0x40, 0xdf, 0x10, 0xa2, 0x40, 0xef, 0x60, 0x23, 0x0d, 0xcf, 0xd9, 0x81, 0x95, 0x22, 0x86, 0x4e,
	0xc9, 0x31, 0xa2, 0x3c, 0x35, 0xc0, 0x0e, 0xad, 0xda, 0x60, 0x3a, 0x27, 0x27, 0xf8, 0xad, 0x1f,
	0xf9, 0x83, 0xd1, 0xb0, 0x61, 0x47, 0x56, 0xef, 0x70, 0xf4, 0x2d, 0x19, 0x4b, 0x05, 0x52, 0x9b,
	0x54, 0x19, 0x7b, 0x48, 0xdf, 0x06, 0x75, 0x49, 0x3a, 0x23, 0x23, 0x24, 0xa0, 0xca, 0x6d, 0x4c,
	0x62, 0x63, 0x62, 0x0a, 0xeb, 0x40, 0x68, 0x6a, 0x09, 0x6c, 0xe0, 0xea, 0x08, 0x18, 0x3b, 0x2b,
	0x04, 0x96, 0x7f, 0xec, 0x3a, 0xb3, 0x80, 0xbe, 0x23, 0x13, 0x51, 0x15, 0xb5, 0xd8, 0x1a, 0xcd,
	0x73, 0x78, 0x28, 0xd6, 0x6c, 0x68, 0xe5, 0x3d, 0x16, 0xbb, 0xa8, 0x00, 0x72, 0xa1, 0x72, 0x50,
	0x18, 0x45, 0x5c, 0x17, 0x31, 0x87, 0xd9, 0x35, 0xa8, 0x1d, 0x28, 0x2e, 0xd9, 0xc8, 0x65, 0x0f,
	0x78, 0xfe, 0xab, 0x47, 0x26, 0xd1, 0xb0, 0x65, 0x51, 0x63, 0x41, 0x46, 0x3d, 0xb5, 0xa3, 0xb6,
	0x80, 0x5e, 0x90, 0x04, 0xcb, 0x6d, 0xc6, 0xec, 0x11, 0x65, 0x64, 0xa0, 0x4c, 0x95, 0x89, 0x3c,
	0x4c, 0x38, 0x40, 0xaf, 0x94, 0xa0, 0xd7, 0x7e, 0xb6, 0x01, 0xd2, 0x4b, 0x32, 0x2c, 0x84, 0x49,
	0x55, 0x9d, 0x55, 0xc6, 0x8f, 0xb4, 0x25, 0xe8, 0x82, 0x1c, 0x89, 0x54, 0xd5, 0x2c, 0x99, 0x1d,
	0x5e, 0x8d, 0xde, 0x4f, 0x17, 0x1d, 0x77, 0x2c, 0x42, 0xb1, 0xe2, 0x2e, 0x5d, 0xd9, 0x38, 0xac,
	0x0c, 0x94, 0x2a, 0xf5, 0xda, 0x8f, 0xd6, 0xa3, 0xf9, 0x8f, 0x84, 0x8c, 0xa2, 0xe8, 0x76, 0xd0,
	0xbd, 0x78, 0xd0, 0x8c, 0x0c, 0x0a, 0x61, 0xb4, 0x49, 0x8d, 0x6f, 0x2c, 0x40, 0x54, 0xaa, 0x27,
	0x21, 0xa1, 0x12, 0xa1, 0x33, 0x0f, 0xd1, 0x16, 0xa5, 0x51, 0x85, 0x54, 0x22, 0xdf, 0x66, 0x78,
	0xa2, 0xeb, 0xaf, 0x4b, 0x76, 0x96, 0xde, 0xdf, 0x5b, 0xba, 0xd7, 0x6c, 0xda, 0xa4, 0xd5, 0x6c,
	0x5e, 0xaf, 0x59, 0x2f, 0x45, 0x66, 0xb1, 0x46, 0xba, 0x24, 0x43, 0x1b, 0x07, 0x9b, 0x4a, 0x78,
	0xc3, 0xb4, 0x44, 0xc7, 0xee, 0xc3, 0xff, 0xd8, 0x9d, 0xfc, 0xc3, 0xee, 0xb8, 0x31, 0xb1, 0x35,
	0xb8, 0xe4, 0x91, 0xdf, 0x98, 0x83, 0xf6, 0x64, 0xfc, 0xdc, 0x81, 0x62, 0x27, 0xfe, 0x64, 0x8f,
	0xb1, 0xa6, 0xac, 0x48, 0x79, 0x69, 0xd3, 0x8e, 0x5d, 0x4d, 0x0d, 0xd1, 0xa8, 0x86, 0x97, 0xc0,
	0x26, 0x91, 0x8a, 0x44, 0xa3, 0x6e, 0x35, 0x28, 0xf6, 0x2c, 0x52, 0x91, 0x68, 0x36, 0xc0, 0x73,
	0x76, 0x1a, 0x6d, 0xc0, 0xd5, 0x63, 0x3f, 0xb1, 0x9e, 0xe7, 0xae, 0x9e, 0x80, 0xd1, 0x0f, 0x5a,
	0x16, 0xb8, 0x16, 0xea, 0xfc, 0xe0, 0xd0, 0xde, 0x63, 0xf1, 0xe2, 0xaf, 0xc7, 0x02, 0xff, 0x7b,
	0x34, 0x68, 0xc9, 0x33, 0xff, 0x9f, 0x45, 0x78, 0xbd, 0x15, 0xa4, 0x79, 0xed, 0xc5, 0x73, 0x77,
	0xbd, 0x23, 0xca, 0x6d, 0x25, 0x78, 0xe1, 0x22, 0x6c, 0x25, 0xf8, 0x00, 0xfd, 0x99, 0xd9, 0x0b,
	0xf2, 0xd2, 0xfb, 0xd3, 0x22, 0x3c, 0xb7, 0x4c, 0x79, 0x15, 0x26, 0xce, 0xdc, 0xb9, 0x11, 0x85,
	0x3b, 0x6b, 0x20, 0x76, 0xfa, 0xca, 0xed, 0x2c, 0xe6, 0x70, 0x46, 0x99, 0x72, 0x2e, 0x9d, 0xba,
	0x19, 0x79, 0x88, 0x79, 0x0b, 0x5e, 0xe1, 0xd1, 0xaf, 0x5d, 0x5e, 0x87, 0x6e, 0xae, 0xc9, 0x39,
	0x17, 0x8b, 0xb5, 0x92, 0x59, 0xf7, 0x6a, 0xdd, 0xd0, 0x0e, 0x5c, 0xe2, 0xdb, 0xbc, 0xec, 0xfd,
	0x3c, 0x38, 0xfc, 0x74, 0xfb, 0xed, 0x3e, 0xb1, 0x4f, 0xf5, 0xf5, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xb8, 0xb9, 0x55, 0xff, 0xbe, 0x05, 0x00, 0x00,
}
